### PR TITLE
Update PublishOpenMV.py

### LINKED ISSUE #25: save a csv of all image names
make csv to save images on openMV

### PR DESCRIPTION
**Pull request by ebgoldstein**
I added 3 things here:

1. I removed the save image function and broke it up. I added a single 'image' folder creation line, and added a single line after the if/else statements to save the image. This removes the redundancy of checking for the image folder each time the save image function is called. I am also saving as a jpg, not bmp.
2. I changed the txt file write/append statement a bit.. 
3. I am saving the state of the memory to the txt file as a debugging step, that might help understand what is going on

### CODE REVIEW

**Comment by ebgoldstein** [comment]
@SUPScientist , pinging you here just so you know about this PR

**Comment by SUPScientist** [comment]
Thanks. Looks clean, and I like the memory state logging idea. Eager to hear how it works.

**Comment by efarq** [comment]
Not deleting this branch until I confirm it works! Thank you Evan!

**Comment by efarq** [comment]
So, with the new code, the openmv wasn't logging data or saving images, which I think was because the memory allocation function output needed to be converted to a string to be saved with on the datalog.txt with the other strings. I fixed this  [#1909160](https://github.com/TinyCamML/Boron-and-OpenMV/commit/19091607839c727c075aa3a415274c732d4bae33) and am trying it out again today!

**Comment by efarq** [comment]
Well, I just ran it successfully for one hour, and then the same issue started occurring. I have attached the datalog.txt, but it's not very helpful, as it looks like it is in a mix of chinese and gibberish. I have also attached the images, which shows that the same thing was happening with the images becoming a 2in1 situation. So I think I'll try adding the sensor.reset information in the while loop to see if that helps. 
[images.zip](https://github.com/user-attachments/files/16336625/images.zip)
[DataLog.txt](https://github.com/user-attachments/files/16336617/DataLog.txt)

**Pull request merged**
